
package com.autodesk.client.model;

import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;


//Generated by http://www.jsonschema2pojo.org/

public class LdapInfo {

    @JsonProperty("ldapEnabled")
    private Boolean ldapEnabled;
    @JsonProperty("domainName")
    private String domainName;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     * No args constructor for use in serialization
     *
     */
    public LdapInfo() {
    }

    /**
     *
     * @param domainName
     * @param ldapEnabled
     */
    public LdapInfo(Boolean ldapEnabled, String domainName) {
        super();
        this.ldapEnabled = ldapEnabled;
        this.domainName = domainName;
    }

    @JsonProperty("ldapEnabled")
    public Boolean getLdapEnabled() {
        return ldapEnabled;
    }

    @JsonProperty("ldapEnabled")
    public void setLdapEnabled(Boolean ldapEnabled) {
        this.ldapEnabled = ldapEnabled;
    }

    @JsonProperty("domainName")
    public String getDomainName() {
        return domainName;
    }

    @JsonProperty("domainName")
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("LdapInfo{");
        sb.append("ldapEnabled=").append(ldapEnabled).append(", ");
        sb.append("domainName=").append(domainName).append(", ");
        sb.append("additionalProperties=").append(additionalProperties);
        sb.append('}');
        return sb.toString();
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalProperties, ldapEnabled, domainName);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        LdapInfo rhs = (LdapInfo) obj;
        return Objects.equals(this.additionalProperties, rhs.additionalProperties)
                && Objects.equals(this.ldapEnabled, rhs.ldapEnabled)
                && Objects.equals(this.domainName, rhs.domainName);
    }

}